### ISSUE TITLE
Cloudstation version not updating

### ISSUE THREAD

**Issue by Xav-Pe** [w0ndersp00n/Chocolatey-Packages#4]
Hello,

The actual version of cloudstation is ``4.3.3-4469``, but chocolatey wants to install the ``4.2.5.4396``, despite [this script](https://github.com/w0ndersp00n/Chocolatey-Packages/blob/master/automatic/cloudstation/update.ps1) is finding the right version.

I'm new to chocolatey and I don't know yet how automatic packages works, but [this line](https://github.com/w0ndersp00n/Chocolatey-Packages/blob/17b0223092387844bf051fa4409029ba3bd8a7d1/automatic/cloudstation/cloudstation.nuspec#L8) or [this one](https://github.com/w0ndersp00n/Chocolatey-Packages/blob/17b0223092387844bf051fa4409029ba3bd8a7d1/automatic/cloudstation/tools/chocolateyInstall.ps1#L4) should maybe be updated.

**Comment by Xav-Pe** [comment]
I created the pull request #5

**Comment by w0ndersp00n** [comment]
Thanks, I've merged it, I'll try to create a package and upload it by tomorrow.

**Comment by w0ndersp00n** [comment]
Latest version is pushed and approved: https://chocolatey.org/packages/cloudstation 😄
